version: "3"
services:
  dev:
    container_name: dev.overseer
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3003"
    volumes:
      - ./:/workspace
      - node_modules:/workspace/node_modules
    environment:
      HOST: 0.0.0.0
    depends_on:
      - db
    command: sleep infinity

volumes:
  node_modules:
