version: "3.8"
services:
  dev:
    container_name: dev.overseer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003"
    volumes:
      - ./:/workspace:cached
      - overseer-node_modules:/workspace/node_modules
      - overseer-build:/workspace/build
    env_file:
      - .devcontainer/.env.devcontainer
    depends_on:
      - db
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  overseer-node_modules:
  overseer-build:
  redis_data: